### ISSUE TITLE
loading data

### ISSUE THREAD

**Issue by norrisan** [scholi/pyOmicron#1]
Hey scholi,

I was wondering if you can help by any chance please.
I was trying to use your software, and seem to have trouble loading data.

![image](https://user-images.githubusercontent.com/40805460/53488222-f6fbaf00-3a8d-11e9-8053-cc150cd44fe4.png)

And I seem to consistently get these errors, maybe I'm doing something simple wrong?

![image](https://user-images.githubusercontent.com/40805460/53488260-172b6e00-3a8e-11e9-83ad-9e581c9c9aeb.png)

**Comment by scholi** [comment]
Hi norrisan,
Glad to see, that the library is used.
The first error is a python error, because you forgot the double quotes as string delimiter.
Now you also don't need to initialize the class twice. So you should do
```python
df = pyOmicron.Matrix("path_to_folder")
```

Now for the second case, you just pass the wrong arguments. As I don't use this library anymore, I never took the time to write a proper documentation, but in the source you will find the following:

```` python
import pyOmicron
import inspect
print(inspect.getsource(pyOmicron.Matrix.plotSTS))

> def plotSTS(self, ID, num=1): # plot STS file called xxx--ID_num.I(V)_mtrx

Hope it will solve your problems. 
Kind regards
Olivier

**Comment by norrisan** [comment]
Hi Oliver,

Thank you so much for the prompt reply and help.I really appreciate it.

Sorry maybe I banged my head this morning, so maybe you can be patient.

My files are:
[image: image.png]

so in my case that should be
20180803_STM_Spectrocopy_2_2_BrAN_on_Au111_210_1.I(V)_mtrx

[image: image.png]


Sorry for the hassle, and thanks in advance.

Andrew

**Comment by scholi** [comment]
Somehow I don't see your images, but here your ID=210 and num=1,
so just do:
```python
df = pyOmicron.Matrix("path_to_folder")
df.getSTSdata(210, 1)
```
and please don't use images for your code. I cannot copy/paste it.
